### PR TITLE
Added save-all function

### PR DESCRIPTION
**Pull request by dreamtigers**
This is the function for #7 to save on launch.

### CODE REVIEW

**Comment by footballhead** [comment]
Thanks for the contribution, looks good! While you're at it, I'd suggest wrapping it up in an option, just in case it messes with someone's workflow.

**Comment by dreamtigers** [comment]
Didn't think it could bug someone's workflow, haha. Moved the config to the package.json file according to Atom's doc, don't know if you mind, and added the option to save all on launch. Let me know what you think.

**Comment by dreamtigers** [comment]
Thanks @Positive07 for the info on how `BufferedProcess` works. Made the fix for #8 using Node's `child_process` to spawn a non buffered process.

**Comment by footballhead** [comment]
Tried it out and it looks fantastic! I'll try to push out an update today. Thank you so much!

Just curious: I can't find documentation on configSchema, where did you get it? All I can dig up is the original commit (https://github.com/atom/atom/commit/2d29fd6e79262bd5b8c902f86456ef5a21f224ae) and this thread with "where is this documented" (https://discuss.atom.io/t/how-do-i-add-settings-to-my-package/26743/14).

**Comment by dreamtigers** [comment]
I found the same "where is this documented", but ended up copying the pattern of their official packages:
* https://github.com/atom/bracket-matcher/blob/master/package.json#L18
* https://github.com/atom/find-and-replace/blob/master/package.json#L56
* https://github.com/atom/grammar-selector/blob/master/package.json#L26
* https://github.com/atom/command-palette/blob/master/package.json#L27

My bad when I said it was according Atom's doc, I apologise.
Btw, could you close the two issues? as they're already solved, if it's not too annoying.

**Comment by footballhead** [comment]
Ah, no worries. I guess the official packages are sorta the source of truth on these things.

I'll take care of the issues, not too much trouble.

**Pull request merged**
